# Generated by Django 3.2 on 2023-06-04 16:34

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230604_2128'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Check the inability to subscribe to yourself',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='Проверка подписки на себя'),
        ),
    ]
