# Generated by Django 3.2 on 2023-06-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230607_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.TextField(default='очень вкусно'),
            preserve_default=False,
        ),
    ]
